### ISSUE TITLE
Question about getting info from daemon

### ISSUE THREAD

**Issue by kpfecteau** [rpush/rpush#526]
Hello, I am working on implementing this gem to send our push notifications but I am running into an issue when trying to get info from rpush running as a daemon.

The config has a comment saying that info can be retrieved by using this method:
`Rpush::Daemon::AppRunner.runners.each do |app_id, runner|`
    `    runner.app`
    `    runner.queue_size`
`end`

but this returns an error stating 
`NoMethodError (undefined method `runners' for `Rpush::Daemon::AppRunner:Class)`

I was wondering what the current method for retrieving this information is.

**Comment by benlangfeld** [comment]
This was broken by f2a3c23f5b6644d602307f5f82789fcf9879f651

**Comment by benlangfeld** [comment]
Does `Rpush::Daemon::AppRunner.status` provide what you need?
